### ISSUE TITLE
FPS drop when half-time highlights begin

### ISSUE THREAD

**Issue by Thinge** [romdi/iosoccer-game#199]
This one might need more info - but we should look out for it. Could be some sort of memory leak?

**Comment by Aryan-5711** [comment]
Doesn't happen for a long time. Also have asked around 10 people if they had this problem and all answers was a flat out no.

**Comment by Aryan-5711** [comment]
Reopening this since I saw this issue happening 2 days ago. I have no idea what caused it. Only thing I know was that there was like almost all Juventus kits (it was Juventus vs Barcelona) and some same keeper kits too. Including some outfield players.
