### ISSUE TITLE
New order of Statistics

### ISSUE THREAD

**Issue by Aryan14** [romdi/iosoccer-game#256]
I found some mobile app (Onefootball) where it showed livescores and it had a very interesting statistics list. 
I know not every statistic is possible to implement in IOS but it's a good list nevertheless.

'%' = percentage count
'#' = number count

My proposed statistics

### General

Possession (%)
Offsides (#)
Corners (#)
Own goals (#)
Distance Covered (#)

### Attack

Goals (#)
Assists (#)
Total shots (#)
Shots on target (#)
Shot accuracy (%)
Blocked shots (#)
Shots on woodwork (#)
Shots from inside the box (#)
Shots from outside the box (#)

### Defence

Tackles (#)
Tackles won (%)
Slide Tackles (#)
Slide Tackles won (%)
Clearances (#)
Interceptions (#)

### Keeper

Saves (#)
Saves caught (%)
Goals conceded (#)

### Distribution

Total passes (#)
Long passes (%)
Passing accuracy (%)
Passing accuracy opp. half (%)
Passing accuracy own. half (%)
Total crosses (#)
Successful crosses (%)

### Discipline

Fouls conceded (#)
Fouls suffered (#)
Yellow cards (#)
Red cards (#)

**Comment by Aryan-5711** [comment]
#General

Possession (%)
Offsides (#)
Corners (#)
Distance Covered (#)

#Attack

Goals (#)
Total shots (#)
Shots on target (#)
Shot accuracy (%)
Blocked shots (#)
Shots on woodwork (#)
Shots from inside the box (#)
Shots from outside the box (#)

#Defence

Tackles (#)
Tackles won (%)
Clearances (#)
Interceptions (#)

#Distribution

Total passes (#)
Long passes (%)
Passing accuracy (%)
Passing accuracy opp. half (%)
Passing accuracy own. half (%)
Total crosses (#)
Successful crosses (%)

#Discipline

Fouls conceded (#)
Fouls suffered (#)
Yellow cards (#)
Red cards (#)
