### ISSUE TITLE
Advantage play improvements

### ISSUE THREAD

**Issue by Aryan14** [romdi/iosoccer-game#273]
Advantage play is a very nice feature in IOSoccer however there are some things that are pretty awkward and need improvement.

When a defender take off an attacker that's about to go 1on1 it would look bad that the player immediately got sent off while the advantage play is ongoing. So we have the following options.
Also has to do when a player is getting a direct red or second yellow.
1. When a player is about to get red card/2nd yellow call the foul immediately and send him off. No matter the advantage.
2. Let the advantage play and if the attacking team scores he only gets yellow at the end of the play. However if the attacking team doesn't score he should be still rewarded with red.
3. Let the advantage play and after the play the fouling player only gets yellow.

**Comment by romdi** [comment]
As discussed, going for Option 2 and not sending the player off until the ball is out for set-piece.
