### ISSUE TITLE
Improve stoppage time rules

### ISSUE THREAD

**Issue by Aryan14** [romdi/iosoccer-game#305]
When injury time exceeded. 2 criteria.
- Did the team who currently has the ball also had the ball before the injury time was exceeded?
- Is it on the opponent's half?

If both 'true' then the game should not be blown for the whistle.

Issue right now is that many potential attacks are unfairly stopped due the current system. Which is that the ball should be around than 20-23 yard from goal. The game should always be stopped if 1 or both criteria are 'false'.

Issues with this suggestion.
- What if the defending team try to clear the ball away but hits the dribbling player? Will it already count for whistle because the defending team already hit the ball for a split second?
- What if the defending team keeps clearing the ball away but not far enough to get past the mid line?

I think solution can be with the current system that during those plays if the ball is outside penalty box while cleared by the defending team it should count for end game. Otherwise not.

**Comment by romdi** [comment]
As discussed:

The game ends when
* there's a kick-off
* defending team has a goal kick
* defending team has a throw-in in their own third
* defending team has a free-kick in their own third
* a keeper catches the ball

Also:
As soon as injury time is over and the ball enters a team's third, the game starts tracking half-way line crosses. As soon as the ball has crossed the half-way line two times the game is over. This means that the defending team can do another counterattack before the match ends, but the previously attacking team can't.

**Comment by romdi** [comment]
After the injury time is over, the game waits for the next touch to occur outside the center third and sets the final attacking team accordingly.
E.g. if the touch occurs in the away team's third (by any player), the final attacking team is set to the home team. 

The game ends when one of the following conditions is true
* The ball leaves the defending team's third
* There's a kick-off after a goal
* Defending team has a goal kick
* Defending team has a throw-in in their own third
* Defending team has a free-kick in their own third
* The defending team's keeper catches the ball
