### ISSUE TITLE
Let players draw on the field during training to plan tactics

### ISSUE THREAD

**Issue by romdi** [romdi/iosoccer-game#328]
What to draw: ![](http://thumbs.dreamstime.com/z/soccer-strategy-drawing-whiteboard-26960394.jpg)

Example of the Dota 2 implementation: ![](http://static.ongamers.com/uploads/scale_super/0/22/954-dota2_ui_coach04.png)

**Comment by Aryan-5711** [comment]
How about a 2D screen like CSGO and draw from there to show the stream viewers?
http://cs.ingame.de/files/2012/10/csgo-gotv-mapoverview.jpg
