### ISSUE TITLE
Restart match vote

### ISSUE THREAD

**Issue by Aryan14** [romdi/iosoccer-game#493]
When we going to have automatic matchmaking (no admins required). There will be for sure a situation where a match starts but still somehow couple of AFKers. A restart vote that would require at least 75% of the votes should solve this. (almost 1 team and a half of the opponent)

Spectators and bench players are not allowed to vote

**Comment by tet4** [comment]
The opposing team wouldn't say yes to that if it was competitive. Maybe
just both teams the option to restart the game once if its before the 5th
minute and no goals scored
